'use client';

import { ShieldCheck, Gavel } from 'lucide-react';

export default function TermsOfServicePage() {
  return (
    <main className="min-h-screen px-6 py-20 bg-background text-foreground">
      <div className="max-w-4xl mx-auto space-y-10">
        <div className="flex items-center gap-2 text-blue-500 mb-4">
          <Gavel className="w-6 h-6" />
          <h1 className="text-3xl font-bold">Terms of Service</h1>
        </div>

        <p className="text-sm text-muted-foreground">
          By accessing LostCryptoHelp or using any of its services, you agree to the following terms and conditions. Please read carefully.
        </p>

        <div className="space-y-6 text-sm leading-relaxed text-zinc-300">
          <section>
            <h2 className="font-semibold text-white mb-2">1. No Financial Advice</h2>
            <p>
              LostCryptoHelp is a technical tool for blockchain analytics and wallet security. We do not offer legal, investment, or financial advice. All risk assessments are generated by AI and should be independently verified.
            </p>
          </section>

          <section>
            <h2 className="font-semibold text-white mb-2">2. No Guarantee of Accuracy</h2>
            <p>
              While we aim to provide reliable insights, we do not guarantee the completeness or accuracy of data presented. Blockchain conditions are dynamic and change rapidly.
            </p>
          </section>

          <section>
            <h2 className="font-semibold text-white mb-2">3. User Responsibility</h2>
            <p>
              Users are solely responsible for actions taken using information from this platform. Always conduct your own due diligence before interacting with contracts or tokens.
            </p>
          </section>

          <section>
            <h2 className="font-semibold text-white mb-2">4. Service Availability</h2>
            <p>
              We reserve the right to modify, suspend, or discontinue the service at any time without notice. Access may be restricted in specific jurisdictions.
            </p>
          </section>

          <section>
            <h2 className="font-semibold text-white mb-2">5. Limitation of Liability</h2>
            <p>
              LostCryptoHelp and its creators shall not be held liable for any loss, damage, or disruption caused by reliance on any data provided on this platform.
            </p>
          </section>
        </div>

        <p className="text-xs text-muted-foreground mt-6">
          If you have any concerns about these terms, please contact us at <strong>support@lostcryptohelp.pro</strong>
        </p>
      </div>
    </main>
  );
}